# test_verify_too_many_args.py
# This should fail.

def x():
    return 42
x(1)